defaults:
  - optimizer: adam
  - language_encoder: sbert

_target_: itpg.policy.models.itpg.ITPG
_recursive_: false

replan_freq: 1
stats_path: null #/home/choudhue/PolicyGuide/dataset/calvin_debug_dataset/stats/dataset.pkl
use_affordance: true
affordance_duration: 10
use_lang_encoding: true
root_data_dir: ${datamodule.root_data_dir}

affordance_checkpoint:
  merged_folder: /home/choudhue/PolicyGuide/dataset/calvin_D_fullT_dataset
  model:
    train_folder: /home/choudhue/PolicyGuide/hydra_outputs/affordance_model/2025-03-25/11-36-18
    model_name: val_err.ckpt
