#!/usr/bin/env python

# Copyright 2024 Columbia Artificial Intelligence, Robotics Lab,
# and The HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
_target_: itpg.policy.models.diffusion_policy.diffusion_policy
n_obs_steps: 2
horizon: 16
n_action_steps: 8

input_shapes:
    default_factory:
        observation:
            image: [3, 96, 96]
        observation:
            state: [2]

output_shapes:
  default_factory:
      action: [2]

# Normalization / Unnormalization
input_normalization_modes:
  default_factory:
      observation:
        image: "mean_std"
      observation:
        state: "min_max"
        
output_normalization_modes: {"action": "min_max"}

# Architecture / modeling.
# Vision backbone.
vision_backbone: "resnet18"
crop_shape: (84, 84)
crop_is_random: True
pretrained_backbone_weights: None
use_group_norm: True
spatial_softmax_num_keypoints: 32
# Unet.
down_dims: (512, 1024, 2048)
kernel_size: 5
n_groups: 8
diffusion_step_embed_dim: 128
use_film_scale_modulation: True
# Noise scheduler.
noise_scheduler_type: "DDPM"
num_train_timesteps: 100
beta_schedule: "squaredcos_cap_v2"
beta_start: 0.0001
beta_end: 0.02
prediction_type: "epsilon"
clip_sample: True
clip_sample_range: 1.0

# Inference
num_inference_steps: None

# Loss computation
do_mask_loss_for_padding: False
