train_folder: ???  # config path to the config.yaml of the training folder (in .hydra)
load_checkpoint: ???
seed: 42
log_dir: /tmp
visualize: True
ep_len: 15
replan_freq: 30
stats_path: null #/home/choudhue/PolicyGuide/dataset/calvin_debug_dataset/stats/dataset.pkl
processes: 1

hydra:
  run:
    dir: ${log_dir}/inference_runs/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
