defaults:
  - datasets: chunked_policy_guide_dataset
  - transforms: play_basic
  - proprioception_dims: robot_no_joints 
  - observation_space: lang_rgb_static_gripper_abs_act
_target_: itpg.datasets.policy_guide_data_module.PolicyGuideDataModule
_recursive_: false
root_data_dir: "/home/choudhue/PolicyGuide/dataset/calvin_D_fullT_dataset"
shuffle_val: false
lang_folder: "lang_annotations"
